insert into product(title, price, description, category, producer, availability, image_path, is_deleted) values
('product1', 100, 'description', 'category1', 'producer2', 'true', 'image_path.jpg', false),
('product2', 50, 'description', 'category1', 'producer1', 'true', 'image_path.jpg', true),
('product3', 130, 'description', 'category2', 'producer2', 'true', 'image_path.jpg', false),
('product4', 70, 'description', 'category1', 'producer1', 'true', 'image_path.jpg', false),
('product5', 60, 'description', 'category2', 'producer1', 'false', 'image_path.jpg', false),
('tovar6', 320, 'description', 'category1', 'producer2', 'true', 'image_path.jpg', false),
('product7', 120, 'description', 'category2', 'producer2', 'true', 'image_path.jpg', false),
('product8', 540, 'description', 'category1', 'producer2', 'true', 'image_path.jpg', false),
('product9', 71, 'description', 'category2', 'producer2', 'false', 'image_path.jpg', false),
('tovar10', 15, 'description', 'category1', 'producer1', 'true', 'image_path.jpg', false),
('product11', 50, 'description', 'category2', 'producer1', 'true', 'image_path.jpg', false),
('product12', 132, 'description', 'category2', 'producer1', 'true', 'image_path.jpg', false),
('tovar13', 123, 'description', 'category1', 'producer1', 'true', 'image_path.jpg', false),
('product14', 44, 'description', 'category1', 'producer2', 'true', 'image_path.jpg', false),
('product15', 17, 'description', 'category2', 'producer2', 'true', 'image_path.jpg', false),
('product16', 79, 'description', 'category2', 'producer1', 'true', 'image_path.jpg', false);